spring:
  datasource:
    url: jdbc:mysql://containers-us-west-70.railway.app:7398/railway?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: w9p2dpMKQ9l3JAdR2AEN
  jpa:
    hibernate:
      ddl-auto: create
  profiles:
    active:
      - db
